### ISSUE TITLE
Cant find obvious reason of failure

### ISSUE THREAD

**Issue by ivankovalenko** [scriptella/scriptella-etl#28]
This file

16.02.2017 23:24:44 <INFO> Execution Progress.Initializing properties: 1%
16.02.2017 23:24:44 <SEVERE> Script /opt/home/ivanko/util/cdr_ivanko/cdr.etl.xml execution failed.

16.02.2017 23:24:44 <SEVERE> Scriptella bug report. Submit to issue tracker.
Scriptella version: 1.1
Exception:
scriptella.execution.EtlExecutorException:
	at scriptella.execution.EtlExecutor.execute(EtlExecutor.java:190)
	at scriptella.tools.launcher.EtlLauncher.execute(EtlLauncher.java:276)
	at scriptella.tools.launcher.EtlLauncher.launch(EtlLauncher.java:193)
	at scriptella.tools.launcher.EtlLauncher.main(EtlLauncher.java:321)
Caused by: java.util.NoSuchElementException
	at java.util.Vector.firstElement(Vector.java:489)
	at oracle.net.resolver.AddrResolution.<init>(AddrResolution.java:223)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:207)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1452)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:496)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:657)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:560)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at scriptella.jdbc.GenericDriver.getConnection(GenericDriver.java:129)
	at scriptella.jdbc.GenericDriver.connect(GenericDriver.java:121)
	at scriptella.jdbc.GenericDriver.connect(GenericDriver.java:104)
	at scriptella.jdbc.GenericDriver.connect(GenericDriver.java:35)
	at scriptella.core.ConnectionManager.getConnection(ConnectionManager.java:81)
	at scriptella.core.Session.<init>(Session.java:57)
	at scriptella.execution.EtlExecutor.prepare(EtlExecutor.java:248)
	at scriptella.execution.EtlExecutor.execute(EtlExecutor.java:178)
	... 3 more
Environment:
{PATH=/usr/java/jdk1.8.0_45//bin:/usr/java/jdk1.6.0_45//bin:/usr/java/jdk1.8.0_45//bin:/home/ivanko/.perl5/bin:/home/ivanko/.sdkman/groovy/current/bin:/usr/java/jdk1.7.0_80//bin:/opt/apache-maven-3.3.9/bin:/home/ivanko/.bin:/opt/apache-ant-1.9.6/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/rvm/bin:/opt/vertica/bin:/home/ivanko/local/scriptella-1.1/bin:/home/ivanko/local/jython-2.5.4rc1/bin:/home/ivanko/local/sqlshell/bin:/home/ivanko/local/grails-3.1.8/bin:/home/ivanko/local/sqlcl/bin:/home/ivanko/.local/bin:/home/ivanko/bin, PERL_MM_OPT=INSTALL_BASE=/home/ivanko/.perl5, HISTCONTROL=ignoredups, SDKMAN_VERSION=3.1.0, TNS_ADMIN=/home/ivanko/.tns_admin, PERL_MB_OPT=--install_base /home/ivanko/.perl5, MAVEN_HOME=/opt/apache-maven-3.3.9, MAIL=/var/spool/mail/ivanko, SDKMAN_BROADCAST_SERVICE=http://cast.sdkman.io, LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib:/usr/lib/oracle/11.2/client64/bin:/home/ivanko/.java_lib, SDKMAN_DIR=/home/ivanko/.sdkman, LOGNAME=ivanko, rvm_version=1.26.11 (master), PWD=/home/ivanko/util/cdr_ivanko, SDKMAN_SERVICE=http://api.sdkman.io, LESSOPEN=||/usr/bin/lesspipe.sh %s, SHELL=/bin/bash, SELINUX_USE_CURRENT_RANGE=, rvm_path=/usr/local/rvm, JYTHON_HOME=/home/ivanko/local/jython-2.5.4rc1, _system_name=RedHat, SCRIPTELLA_HOME=/home/ivanko/local/scriptella-1.1, LS_COLORS=no=00:fi=00:di=00;96:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.flac=01;35:*.mp3=01;35:*.mpc=01;35:*.ogg=01;35:*.wav=01;35:, SHLVL=2, SDKMAN_BROKER_SERVICE=http://broker.sdkman.io, _system_arch=x86_64, rvm_bin_path=/usr/local/rvm/bin, LDAPCON=jdbc:oracle:thin:@ldap://oid2.#ENTRY#:389/cn=OracleContext,dc=#ENTRY#,dc=com/#ENTRY#, HISTSIZE=1000, JAVA_HOME=/usr/java/jdk1.8.0_45/, TERM=xterm-256color, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt, rvm_prefix=/usr/local, LANG=ru_RU.UTF-8, XDG_SESSION_ID=2698, SELINUX_LEVEL_REQUESTED=, ANT_HOME=/opt/apache-ant-1.9.6, GROOVY_HOME=/home/ivanko/.sdkman/groovy/current, SELINUX_ROLE_REQUESTED=, ORACLE_HOME=/usr/lib/oracle/11.2/client64, PERL5LIB=/home/ivanko/.perl5/lib/perl5:, _=/usr/java/jdk1.8.0_45//bin/java, HOSTALIASES=/home/ivanko/.hosts, SQLPATH=/home/ivanko/.sqlplus, _system_type=Linux, CVS_RSH=ssh, SSH_TTY=/dev/pts/2, SSH_CLIENT=172.27.44.24 57513 22, _system_version=7, SDKMAN_PLATFORM=Linux, USER=ivanko, CLASSPATH=:/home/ivanko/.java_lib/javaeditline.jar:/home/ivanko/.java_lib/ojdbc7_g.jar:/home/ivanko/.java_lib/ojdbc7.jar, SSH_CONNECTION=172.27.44.24 57513 172.16.44.121 22, HOSTNAME=vm-ivanko.#ENTRY#.com, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, XDG_RUNTIME_DIR=/run/user/563, PERL_LOCAL_LIB_ROOT=:/home/ivanko/.perl5, HOME=/home/ivanko}
System properties:
{java.runtime.name=Java(TM) SE Runtime Environment, sun.boot.library.path=/usr/java/jdk1.8.0_45/jre/lib/amd64, java.vm.version=25.45-b02, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, path.separator=:, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, user.country=RU, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/opt/home/ivanko/util/cdr_ivanko, java.runtime.version=1.8.0_45-b14, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, java.endorsed.dirs=/usr/java/jdk1.8.0_45/jre/lib/endorsed, os.arch=amd64, java.io.tmpdir=/tmp, line.separator=
, java.vm.specification.vendor=Oracle Corporation, os.name=Linux, sun.jnu.encoding=UTF-8, java.library.path=/usr/lib/oracle/11.2/client64/lib:/usr/lib/oracle/11.2/client64/bin:/home/ivanko/.java_lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, java.specification.name=Java Platform API Specification, java.class.version=52.0, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=3.10.0-327.el7.x86_64, user.home=/home/ivanko, user.timezone=Europe/Moscow, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=UTF-8, java.specification.version=1.8, java.class.path=:/home/ivanko/local/scriptella-1.1/lib/commons-jexl.jar:/home/ivanko/local/scriptella-1.1/lib/commons-logging.jar:/home/ivanko/local/scriptella-1.1/lib/ojdbc6.jar:/home/ivanko/local/scriptella-1.1/lib/scriptella-core.jar:/home/ivanko/local/scriptella-1.1/lib/scriptella-drivers.jar:/home/ivanko/local/scriptella-1.1/lib/scriptella-tools.jar:/home/ivanko/local/scriptella-1.1/scriptella.jar, user.name=ivanko, java.vm.specification.version=1.8, sun.java.command=scriptella.tools.launcher.EtlLauncher cdr.etl.xml, java.home=/usr/java/jdk1.8.0_45/jre, sun.arch.data.model=64, user.language=ru, java.specification.vendor=Oracle Corporation, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, java.version=1.8.0_45, java.ext.dirs=/usr/java/jdk1.8.0_45/jre/lib/ext:/usr/java/packages/lib/ext, sun.boot.class.path=/usr/java/jdk1.8.0_45/jre/lib/resources.jar:/usr/java/jdk1.8.0_45/jre/lib/rt.jar:/usr/java/jdk1.8.0_45/jre/lib/sunrsasign.jar:/usr/java/jdk1.8.0_45/jre/lib/jsse.jar:/usr/java/jdk1.8.0_45/jre/lib/jce.jar:/usr/java/jdk1.8.0_45/jre/lib/charsets.jar:/usr/java/jdk1.8.0_45/jre/lib/jfr.jar:/usr/java/jdk1.8.0_45/jre/classes, java.vendor=Oracle Corporation, file.separator=/, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, sun.io.unicode.encoding=UnicodeLittle, sun.cpu.endian=little, sun.cpu.isalist=}
-----------------------------------------------------------------
``

**Comment by ivankovalenko** [comment]
wrong configuration. sorry my bad.
