### ISSUE TITLE
Janino Driver 3.11 fails

### ISSUE THREAD

**Issue by ivankovalenko** [scriptella/scriptella-etl#30]
Dec 18, 2018 7:07:18 AM <SEVERE> Scriptella bug report. Submit to issue tracker.
Scriptella version: 1.1
Exception:
scriptella.execution.EtlExecutorException: org.codehaus.commons.compiler.Location.getLineNumber()S
	at scriptella.execution.EtlExecutor.execute(EtlExecutor.java:190)
	at scriptella.tools.launcher.EtlLauncher.execute(EtlLauncher.java:276)
	at scriptella.tools.launcher.EtlLauncher.launch(EtlLauncher.java:193)
	at scriptella.tools.launcher.EtlLauncher.main(EtlLauncher.java:321)
Caused by: java.lang.NoSuchMethodError: org.codehaus.commons.compiler.Location.getLineNumber()S
	at scriptella.driver.janino.CodeCompiler.guessErrorStatement(CodeCompiler.java:99)
	at scriptella.driver.janino.CodeCompiler.compile(CodeCompiler.java:75)
	at scriptella.driver.janino.CodeCompiler.compileScript(CodeCompiler.java:47)
	at scriptella.driver.janino.JaninoConnection.executeScript(JaninoConnection.java:44)
	at scriptella.core.ScriptExecutor.execute(ScriptExecutor.java:49)
	at scriptella.core.ContentExecutor.execute(ContentExecutor.java:73)
	at scriptella.core.ElementInterceptor.executeNext(ElementInterceptor.java:56)
	at scriptella.core.StatisticInterceptor.execute(StatisticInterceptor.java:41)
	at scriptella.core.ElementInterceptor.executeNext(ElementInterceptor.java:56)
	at scriptella.core.ConnectionInterceptor.execute(ConnectionInterceptor.java:36)
	at scriptella.core.ElementInterceptor.executeNext(ElementInterceptor.java:56)
	at scriptella.core.ExceptionInterceptor.execute(ExceptionInterceptor.java:39)
	at scriptella.core.Session.execute(Session.java:103)
	at scriptella.execution.EtlExecutor.execute(EtlExecutor.java:227)
	at scriptella.execution.EtlExecutor.execute(EtlExecutor.java:183)
	... 3 more
Environment:
{TERM=xterm-256color, JAVA_HOME=/usr/java/jdk1.7.0_80/, MAIL=/var/spool/mail/ivanko, SCRIPTELLA_HOME=/home/ivanko/local/scriptella-1.1, ORACLE_HOME=/usr/lib/oracle/11.2/client64, SHLVL=2, MAVEN_HOME=/opt/apache-maven-3.3.9, _system_arch=x86_64, JAVA_OPTS=-server, SSH_TTY=/dev/pts/4, TNS_ADMIN=/home/ivanko/.tns_admin, LOGNAME=ivanko, LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib:/usr/lib/oracle/11.2/client64/bin:/home/ivanko/.java_lib, CLASSPATH=:/home/ivanko/.java_lib/javaeditline.jar:/home/ivanko/.java_lib/ojdbc7_g.jar:/home/ivanko/.java_lib/ojdbc7.jar:/home/ivanko/.java_lib/sqlite-jdbc-3.21.0.jar, ANT_HOME=/opt/apache-ant-1.9.6, USER=ivanko, HISTCONTROL=ignoredups, HOME=/home/ivanko, LANG=en_US.UTF-8}
System properties:
{java.runtime.name=Java(TM) SE Runtime Environment, sun.boot.library.path=/usr/java/jdk1.7.0_80/jre/lib/amd64, java.vm.version=24.80-b11, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, path.separator=:, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, user.country=US, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/opt/home/ivanko/TS7552, java.runtime.version=1.7.0_80-b15, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, java.endorsed.dirs=/usr/java/jdk1.7.0_80/jre/lib/endorsed, os.arch=amd64, java.io.tmpdir=/tmp, line.separator=
, java.vm.specification.vendor=Oracle Corporation, os.name=Linux, sun.jnu.encoding=UTF-8, java.library.path=/usr/lib/oracle/11.2/client64/lib:/usr/lib/oracle/11.2/client64/bin:/home/ivanko/.java_lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, java.specification.name=Java Platform API Specification, java.class.version=51.0, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=3.10.0-327.el7.x86_64, user.home=/home/ivanko, user.timezone=Europe/Moscow, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=UTF-8, java.specification.version=1.7, java.class.path=:/home/ivanko/local/scriptella-1.1/lib/commons-compiler-3.0.11.jar:/home/ivanko/local/scriptella-1.1/lib/commons-jexl.jar:/home/ivanko/local/scriptella-1.1/lib/commons-logging.jar:/home/ivanko/local/scriptella-1.1/lib/janino-3.0.11.jar:/home/ivanko/local/scriptella-1.1/lib/ojdbc7.jar:/home/ivanko/local/scriptella-1.1/lib/scriptella-core.jar:/home/ivanko/local/scriptella-1.1/lib/scriptella-drivers.jar:/home/ivanko/local/scriptella-1.1/lib/scriptella-tools.jar:/home/ivanko/local/scriptella-1.1/scriptella.jar, user.name=ivanko, java.vm.specification.version=1.7, sun.java.command=scriptella.tools.launcher.EtlLauncher ts_replys.etl.xml, java.home=/usr/java/jdk1.7.0_80/jre, sun.arch.data.model=64, user.language=en, java.specification.vendor=Oracle Corporation, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, java.version=1.7.0_80, java.ext.dirs=/usr/java/jdk1.7.0_80/jre/lib/ext:/usr/java/packages/lib/ext, sun.boot.class.path=/usr/java/jdk1.7.0_80/jre/lib/resources.jar:/usr/java/jdk1.7.0_80/jre/lib/rt.jar:/usr/java/jdk1.7.0_80/jre/lib/sunrsasign.jar:/usr/java/jdk1.7.0_80/jre/lib/jsse.jar:/usr/java/jdk1.7.0_80/jre/lib/jce.jar:/usr/java/jdk1.7.0_80/jre/lib/charsets.jar:/usr/java/jdk1.7.0_80/jre/lib/jfr.jar:/usr/java/jdk1.7.0_80/jre/classes, java.vendor=Oracle Corporation, file.separator=/, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, sun.io.unicode.encoding=UnicodeLittle, sun.cpu.endian=little, sun.cpu.isalist=}
-----------------------------------------------------------------

**Comment by ejboy** [comment]
Should be fixed with 1.2
