### ISSUE TITLE
Scriptella fails with Janino 2.7.8

### ISSUE THREAD

**Issue by ldcasillas-progreso** [scriptella/scriptella-etl#6]
Feb 4, 2015 4:30:57 PM <SEVERE> Scriptella bug report. Submit to issue tracker.
    Scriptella version: 1.1
    Exception: 
    scriptella.execution.EtlExecutorException: org/codehaus/commons/compiler/IScriptEvaluator
    	at scriptella.execution.EtlExecutor.execute(EtlExecutor.java:190)
    	at scriptella.tools.launcher.EtlLauncher.execute(EtlLauncher.java:276)
    	at scriptella.tools.launcher.EtlLauncher.launch(EtlLauncher.java:193)
    	at scriptella.tools.launcher.EtlLauncher.main(EtlLauncher.java:321)
    Caused by: java.lang.NoClassDefFoundError: org/codehaus/commons/compiler/IScriptEvaluator
    	at java.lang.ClassLoader.defineClass1(Native Method)
    	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    	at java.lang.Class.forName0(Native Method)
    	at java.lang.Class.forName(Class.java:190)
    	at scriptella.driver.janino.Driver.<init>(Driver.java:36)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    	at java.lang.Class.newInstance(Class.java:374)
    	at scriptella.core.DriverFactory.getDriver(DriverFactory.java:96)
    	at scriptella.core.DriverFactory.getDriver(DriverFactory.java:58)
    	at scriptella.core.ConnectionManager.<init>(ConnectionManager.java:70)
    	at scriptella.core.Session.<init>(Session.java:51)
    	at scriptella.execution.EtlExecutor.prepare(EtlExecutor.java:248)
    	at scriptella.execution.EtlExecutor.execute(EtlExecutor.java:178)
    	... 3 more
    Caused by: java.lang.ClassNotFoundException: org.codehaus.commons.compiler.IScriptEvaluator
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    	... 29 more
    Environment: 
    {HADOOP_PREFIX=/Users/luis.casillas/Software/hadoop-2.4.1, DYLD_LIBRARY_PATH=/usr/local/mysql/lib, EMR_HOME=/Users/luis.casillas/Software/elastic-mapreduce-cli, JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home, SHLVL=2, __CF_USER_TEXT_ENCODING=0x6DE505F7:0:0, EMR_SSH_KEY=/Users/luis.casillas/Software/elastic-mapreduce-cli/LuisCasillas.pem, EMR_SSH_OPTS=-i /Users/luis.casillas/Software/elastic-mapreduce-cli/LuisCasillas.pem -o StrictHostKeyChecking=no -o ServerAliveInterval=30, LINGUAL_PLATFORM=hadoop2-mr1, PWD=/Users/luis.casillas/Source/credit-profile-scrub-and-load/src/main/scripts/scriptella, LOGNAME=luis.casillas, LINGUAL_HOME=/Users/luis.casillas/.lingual-client, _=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/bin/java, SSH_AUTH_SOCK=/tmp/launch-1aR55Q/Listeners, __CHECKFIX1436934=1, HADOOP_HOME=/Users/luis.casillas/Software/hadoop-2.4.1, TEZ_JARS=/Users/luis.casillas/Software/apache-tez-0.5.1, TEZ_CONF_DIR=/Users/luis.casillas/Software/hadoop-2.4.1/etc/hadoop, SHELL=/bin/bash, TMPDIR=/var/folders/xq/khbxznb55f58rs735ngcz3dspy_1gq/T/, JAVA_MAIN_CLASS_13796=scriptella.tools.launcher.EtlLauncher, SECURITYSESSIONID=186a4, PATH=/Users/luis.casillas/Software/scriptella/scriptella-1.1/bin:/Users/luis.casillas/Software/elastic-mapreduce-cli:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Users/luis.casillas/Software/hadoop-2.4.1/bin:/Users/luis.casillas/Software/elastic-mapreduce-cli:/Users/luis.casillas/.lingual-client/bin, EMR_SSH_KEY_NAME=LuisCasillas, VERSIONER_PYTHON_VERSION=2.7, COMMAND_MODE=unix2003, ELASTIC_MAPREDUCE_CREDENTIALS=/Users/luis.casillas/Software/elastic-mapreduce-cli/credentials.json, USER=luis.casillas, HADOOP_CLASSPATH=/Users/luis.casillas/Software/hadoop-2.4.1/etc/hadoop:/Users/luis.casillas/Software/apache-tez-0.5.1/*:/Users/luis.casillas/Software/apache-tez-0.5.1/lib/*, HOME=/Users/luis.casillas, BASH_EMR=/Users/luis.casillas/Software/bash-emr, Apple_PubSub_Socket_Render=/tmp/launch-X7hSff/Render, SCRIPTELLA_HOME=/Users/luis.casillas/Software/scriptella/scriptella-1.1, HADOOP_CONF_DIR=/Users/luis.casillas/Software/hadoop-2.4.1/etc/hadoop, VERSIONER_PYTHON_PREFER_32_BIT=no}
    System properties: 
    {java.runtime.name=Java(TM) SE Runtime Environment, sun.boot.library.path=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib, java.vm.version=24.51-b03, gopherProxySet=false, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, path.separator=:, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, user.country=US, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/Users/luis.casillas/Source/credit-profile-scrub-and-load/src/main/scripts/scriptella, java.runtime.version=1.7.0_51-b13, java.awt.graphicsenv=sun.awt.CGraphicsEnvironment, java.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/endorsed, os.arch=x86_64, java.io.tmpdir=/var/folders/xq/khbxznb55f58rs735ngcz3dspy_1gq/T/, line.separator=
    , java.vm.specification.vendor=Oracle Corporation, os.name=Mac OS X, sun.jnu.encoding=UTF-8, java.library.path=/usr/local/mysql/lib:/Users/luis.casillas/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:., java.specification.name=Java Platform API Specification, java.class.version=51.0, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=10.9.5, http.nonProxyHosts=local|*.local|169.254/16|*.169.254/16, user.home=/Users/luis.casillas, user.timezone=America/Los_Angeles, java.awt.printerjob=sun.lwawt.macosx.CPrinterJob, file.encoding=US-ASCII, java.specification.version=1.7, java.class.path=:/Users/luis.casillas/Software/scriptella/scriptella-1.1/lib/commons-jexl.jar:/Users/luis.casillas/Software/scriptella/scriptella-1.1/lib/commons-logging.jar:/Users/luis.casillas/Software/scriptella/scriptella-1.1/lib/janino.jar:/Users/luis.casillas/Software/scriptella/scriptella-1.1/lib/mysql-connector-java-5.1.21.jar:/Users/luis.casillas/Software/scriptella/scriptella-1.1/lib/ojdbc6.jar:/Users/luis.casillas/Software/scriptella/scriptella-1.1/lib/postgresql-8.4-703.jdbc4.jar:/Users/luis.casillas/Software/scriptella/scriptella-1.1/lib/scriptella-core.jar:/Users/luis.casillas/Software/scriptella/scriptella-1.1/lib/scriptella-drivers.jar:/Users/luis.casillas/Software/scriptella/scriptella-1.1/lib/scriptella-tools.jar, user.name=luis.casillas, java.vm.specification.version=1.7, sun.java.command=scriptella.tools.launcher.EtlLauncher load_response.etl.xml, java.home=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre, sun.arch.data.model=64, user.language=en, java.specification.vendor=Oracle Corporation, awt.toolkit=sun.lwawt.macosx.LWCToolkit, java.vm.info=mixed mode, java.version=1.7.0_51, java.ext.dirs=/Users/luis.casillas/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java, sun.boot.class.path=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/classes, java.vendor=Oracle Corporation, file.separator=/, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, sun.io.unicode.encoding=UnicodeBig, sun.cpu.endian=little, socksNonProxyHosts=local|*.local|169.254/16|*.169.254/16, ftp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16, sun.cpu.isalist=}
    ----------------------------------------------------------------

**Comment by bhuesemann** [comment]
Hi,

I think you may not have the commons-compiler.jar from the janino package included in the class path. Please note that it is called commons-compiler.jar in the janino distribution zip and janino-commons-compiler.jar in the scriptella lib dir.

Bodo

**Comment by bhuesemann** [comment]
Please close the issue or comment.
